# Generated by Django 3.2.5 on 2021-08-12 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('restauro_id', models.CharField(max_length=10)),
                ('dish', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('orderdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
