# Generated by Django 3.2.5 on 2021-08-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='addres',
            new_name='address',
        ),
    ]
