# Generated by Django 3.2.5 on 2021-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_addres_userextension_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='usertype',
            field=models.CharField(choices=[('C', 'Normal User'), ('R', 'Restaurant')], max_length=1),
        ),
    ]
