# Generated by Django 3.2.5 on 2021-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_userextension_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='usertype',
            field=models.CharField(choices=[('C', 'Customer'), ('R', 'Restaurant')], max_length=1),
        ),
    ]
